server {
    listen 5174;
    root /usr/share/nginx/html;
    index index.html;

    # Allow shell origin to fetch remoteEntry.js and chunks
    add_header Access-Control-Allow-Origin *;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
