[tox]
envlist = py312, lint, typecheck
skipsdist = true

[testenv]
allowlist_externals = poetry
commands_pre = poetry install --no-root
commands = poetry run pytest {posargs}

[testenv:lint]
commands_pre = poetry install --no-root
commands =
    poetry run ruff check src/ tests/
    poetry run ruff format --check src/ tests/

[testenv:typecheck]
commands_pre = poetry install --no-root
commands = poetry run mypy src/
